<?php
/**
 * @file
 * Contains cms_custom_module_openweather.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

function cms_custom_module_openweather_page_attachments_alter(&$page){

  $path = $current_path = \Drupal::service('path.current')->getPath();
  $result = \Drupal::service('path.alias_manager')->getAliasByPath($current_path);
  $page['#attached']['library'][] = 'cms_custom_module_openweather/cms_custom_module_openweather';
}

/**
 * Implements hook_theme().
 */
function cms_custom_module_openweather_theme($existing, $type, $theme, $path) {
  return array(
    'openweather' => array(
      'variables' => array('openweather_detail' => NULL, 'cms_custom_module_form' => NULL),
     // 'cms_custom_module_openweather_form' => ('render element' => 'form'),
    ),
    'openweather_hourlyforecast' => array(
      'variables' => array('hourlyforecast_detail' => NULL),
    ),
    'openweather_dailyforecast' => array(
      'variables' => array('dailyforecast_detail' => NULL),
    ),
  );
}
