<?php

/**
 * @file
 * Contains websocket_task.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function websocket_task_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the websocket_task module.
    case 'help.page.websocket_task':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is a Development version of a websocket example') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function websocket_task_theme() {
  return [
    'chat_block1' => [
      'variables' => [
        'form' => '',
      ],
      'template' => 'block--chat-block',
    ],
    'chat_block2' => [
      'variables' => [
        'form' => '',
      ],
      'template' => 'block--chat-block',
    ],
  ];
}
